<?php

namespace poursuiteEtudes\FormationsBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EtudiantRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EtudiantRepository extends EntityRepository
{
    public function findByEtudiantOrder ($order, $type)
    {
        $requete=$this->_em->createQueryBuilder()
            ->select('e')
            ->from($this->_entityName, 'e')
            //->lefjoin('poursuiteEtudesFormationsBundle:Filiere', 'f', 'WITH' ,'e.filiere = f.id ')
            ->join('e.filiere', 'f')
            ->join('e.grillemoyenne', 'gm')
            ->addSelect('f')
            ->addSelect('gm')
            ->orderBy($order, $type)
            ;
        $query = $requete->getQuery();
        return $query->getResult();
    }

    public function findByFilter ($annee,$sigleEcole, $sigleLicence, $order='e.nom', $type='ASC')
    {
        $requete=$this->_em->createQueryBuilder()
            ->select('e')
            ->from($this->_entityName, 'e')
            //->lefjoin('poursuiteEtudesFormationsBundle:Filiere', 'f', 'WITH' ,'e.filiere = f.id ')
            ->join('e.filiere', 'f')
            ->join('f.formation', 'fo')
            ->addSelect('f')
            ->addSelect('fo')
            ->orderBy($order,$type);
            ;
            
        if (!is_null ($annee))
        {
            $requete-> andWhere ('e.anneeDiplome= :annee')
                    ->setParameter('annee', $annee)
                    ;
        }
        
      if (!is_null ($sigleEcole))
        {
            $requete->andWhere ('fo.id= :sigle')
                    ->setParameter('sigle', $sigleEcole)
                    ;
        }
        
        $query = $requete->getQuery();
        return $query->getResult();
    }
    
    public function findAnnee ($type='ASC')
    {
        $requete=$this->_em->createQueryBuilder()
            ->select('e.anneeDiplome')
            ->from($this->_entityName, 'e')
            ->distinct()
            ->orderBy ('e.anneeDiplome', $type)
        ;
        
        $query = $requete->getQuery();
        return $query->getResult();
    }
    
}