<?php

namespace poursuiteEtudes\FormationsBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * FormationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FormationRepository extends EntityRepository
{
        public function findNiveau ($type='ASC')
    {
        $requete=$this->_em->createQueryBuilder()
            ->select('fo.niveau')
            ->from($this->_entityName, 'fo')
            ->distinct()
            ->orderBy ('fo.niveau', $type)
        ;
        
        $query = $requete->getQuery();
        return $query->getResult();
    }
    
    public function findEcole ($type='ASC')
    {
         $requete=$this->_em->createQueryBuilder()
            ->select('fo')
            ->from($this->_entityName, 'fo')
            ->distinct()
            ->orderBy ('fo.nomComplet', $type)
        ;
        
        $query = $requete->getQuery();
        return $query->getResult();
    }
}
