<?php

namespace poursuiteEtudes\FormationsBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * GrilleMoyenneRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GrilleMoyenneRepository extends EntityRepository
{
}
