<?php

namespace poursuiteEtudes\FormationsBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MetierViseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MetierViseRepository extends EntityRepository
{
}
